### ISSUE TITLE
Destroy does not remove domain definitions

### ISSUE THREAD

**Issue by grossjo** [basak/uvtool#1]
Not sure if this was on purpose, or if this the active source for ubuntu.

But it you do 
`uvt-kvm destroy domain_name`

it leaves around the domain definition.

Was this on purpose?

**Comment by basak** [comment]
It should remove the domain definition but if you have customised it then it may not. The use case of "create, destroy" should not leave anything behind but the use case of "create, manipulate libvirt, destroy" or "create with advanced libvirt options", destroy" may do.

If you're using uvtool on Ubuntu then please could you re-file at https://bugs.launchpad.net/ubuntu/+source/uvtool/+filebug? I should remove this tracker. Sorry for the confusion.

(for uvtool not on Ubuntu the right place is https://bugs.launchpad.net/uvtool/+filebug)

**Comment by basak** [comment]
Turning off issues makes this one disappear and I'm worried you won't be able to see my reply. Can you let me know when you see this reply please, and then I'll turn off Issues again permanently?

**Comment by grossjo** [comment]
I got this reply. Thank you.
I'll follow up if its an actual bug in the right place.

**Comment by basak** [comment]
Thank you for confirming. I'll remove issues from this repository now.
